// Generated by CoffeeScript 1.9.0
(function() {
  var EntUITabText;

  EntUITabText = (function() {
    function EntUITabText(target, prefix, meta, callbacks, parent_type, parent_id) {
      this.target = target;
      this.prefix = prefix;
      this.meta = meta;
      this.callbacks = callbacks;
      this.parent_type = parent_type;
      this.parent_id = parent_id;
    }

    EntUITabText.prototype.build = function() {
      this.target.empty();
      if (this.meta.text) {
        return this.target.text(this.meta.text);
      }
    };

    return EntUITabText;

  })();

  EntUI.prototype.EntUI_tab_text = EntUITabText;

}).call(this);
